version: '3'
services:
  web:
    # platform: linux/amd64
    image: nginx:1.21
    ports:
      - "83:80"
    depends_on:
      - app
    volumes:
      - ./nginx/etc/nginx/conf.d:/etc/nginx/conf.d
      - ./src:/var/www/html
  app:
    # platform: linux/amd64
    build: ./php
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html
  db:
    platform: linux/amd64
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3305:3306"
    volumes:
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/etc/mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
    

# docker-compose.yml
version: '3'

services:
  web:
    container_name: docker-compose-mailhog-web
    build: ./php
    ports:
      - '80:80'
    volumes:
      - ../html:/var/www/html
    hostname: localhost
    networks:
      - br0
  # mailhogの設定を追記
  mailhog:
    container_name: docker-compose-mailhog-mailhog
    image: 'mailhog/mailhog:latest'
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - br0

networks:
  br0:
    driver: bridge
